### PR TITLE
Document the inactive status of the project

### PR DESCRIPTION
**Pull request by rillig**

### CODE REVIEW

**Comment by behdad** [comment]
I still like to review your big PR and merge but I just don't have time to do any meaningful review.  I might ask someone else.

**Comment by behdad** [comment]
I'd be happy to merge a PR that documents your fork however!

**Comment by dcecile** [comment]
@behdad The README says that this project was used by Web Fonts and Chrome for font manipulation, but since this project is no longer being developed, have Web Fonts and Chrome switched to a different font-manipulation library?

**Comment by behdad** [comment]
> @behdad The README says that this project was used by Web Fonts and Chrome for font manipulation, but since this project is no longer being developed, have Web Fonts and Chrome switched to a different font-manipulation library?

Chrome still uses sfntly C++ part for subsetting.  Google Fonts uses sfntly only to convert to EOT. For subsetting and other needs they now use http://github.com/fonttools/fonttools

**Pull request merged**
