### PR TITLE
Various improvements and cleanups

### PR DESCRIPTION
**Pull request by rillig**

### CODE REVIEW

**Comment by rillig** [comment]
These commits are just for your consideration. If you have any comments, feel free to leave them at the commits. I'm experienced at rebasing and managing commits before pushing them. :)

**Comment by behdad** [comment]
Hi,

Thanks for your work.  Currently sfntly is unmaintained, so I'm reluctant to merge non-bug-fix improvements.  I suggest you keep a fork for now.

Thanks!

**Comment by rillig** [comment]
Could you please copy the above statements about the project state to the `README.md` file so that they are prominently displayed? This would have saved me several weekends of work.

Thanks,
Roland

**Comment by davelab6** [comment]
Roland, I'm very grateful for your work. I propose to add a link to your
fork in the readme, to point others to you so your effort isn't wasted.

**Comment by rillig** [comment]
Sure, that would be nice. I'll definitely keep the repository since I learned a lot about OpenType fonts while writing the font viewer, and I think it might be useful for others, too.

**Comment by behdad** [comment]
Thanks.  Please don't delete your branch!

**Comment by rillig** [comment]
The branch continues as `rillig:master`, since now every commit is official by definition, and not work in progress. :)

**Pull request closed without merging**
